import Head from 'next/head';
import tw from 'twin.macro';

const Title = tw.h1`text-red-500`;
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Title>Hello World</Title>
			</main>
		</div>
	);
}
